### ISSUE TITLE
[recovery] NanoDroid patcher fails

### ISSUE THREAD

**Issue by Loader009** [tdm/android_device_fxtec_pro1#14]
Sideloading the NanoDroid-patcher-22.5.1.20200102.zip works but fails.
Be sure to remount,rw /system_root in order to modify the root partition, if you want to try it out.
If you have an idea of how to circumvent this issue, please say so.
I'll do more research tomorrow, if this is a NanoDroid issue.

```
[  906.899022] /sideload/package.zip opened
[  906.899030] creating directory: META-INF/
[  906.899038] creating directory: META-INF/com/
[  906.899046] creating directory: META-INF/com/google/
[  906.899054] creating directory: META-INF/com/google/android/
[  906.899061]  extracting: META-INF/com/google/android/updater-script
[  906.899069]  extracting: META-INF/com/google/android/update-binary
[  906.899077] creating directory: dexpatcher/
[  906.899085]  extracting: dexpatcher/core_services.jar.dex
[  906.899093]  extracting: dexpatcher/hook_4.1-6.0_services.jar.dex
[  906.899101]  extracting: dexpatcher/hook_7.0-9.0_services.jar.dex
[  906.899110]  extracting: dexpatcher/baksmali_26.dex
[  906.899117]  extracting: dexpatcher/smali_26.dex
[  906.899125]  extracting: dexpatcher/baksmali_25.dex
[  906.899133]  extracting: dexpatcher/smali_25.dex
[  906.899141]  extracting: dexpatcher/smali_23.dex
[  906.899149]  extracting: dexpatcher/baksmali_23.dex
[  906.899156]  extracting: dexpatcher/70-nanodroidpatcher.sh
[  906.899164]  extracting: dexpatcher/org.spoofing.apk
[  906.899172]  extracting: dexpatcher/dexpatcher.dex
[  906.899180]  extracting: dexpatcher/file.arm
[  906.899188]  extracting: dexpatcher/file.x86
[  906.899196]  extracting: dexpatcher/vdexExtractor.arm
[  906.899204]  extracting: dexpatcher/vdexExtractor.arm64
[  906.899212]  extracting: dexpatcher/vdexExtractor.x86
[  906.899220]  extracting: dexpatcher/vdexExtractor.x86_64
[  906.899229]  extracting: dexpatcher/zip.arm
[  906.899237]  extracting: dexpatcher/zip.x86
[  906.899245]  extracting: dexpatcher/magic.mgc
[  906.899253]  extracting: ChangeLog.md
[  906.899261]  extracting: README.md
[  906.899269]  extracting: busybox.arm
[  906.899277]  extracting: busybox.x86
[  906.899285]  extracting: CommonPatcher
[  910.265564] Exception in thread "main" java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/cli/Options;
[  910.265792] 	at lanchon.dexpatcher.Parser.getOptions(Parser.java:152)
[  910.265988] 	at lanchon.dexpatcher.Parser.parseCommandLine(Parser.java:39)
[  910.266173] 	at lanchon.dexpatcher.Main.runWithExceptions(Main.java:68)
[  910.266364] 	at lanchon.dexpatcher.Main.run(Main.java:49)
[  910.266549] 	at lanchon.dexpatcher.Main.run(Main.java:44)
[  910.266733] 	at lanchon.dexpatcher.Main.runWithUsage(Main.java:39)
[  910.266925] 	at lanchon.dexpatcher.Main.main(Main.java:30)
[  910.267164] Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.cli.Options" on path: DexPathList[[dex file "/dev/tmp/install/dexpatcher/dexpatcher.dex"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/vendor/lib64, /system/lib64, /vendor/lib64, /system/vendor/lib64]]
[  910.267363] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
[  910.267549] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[  910.267735] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[  910.267900] 	... 7 more
[  910.539778] E:Error in /sideload/package.zip (Status 1)
```

PS: For those unaware of NanoDroid (formerly known as NanoMod); it is an alternative way to use Google apps without the real Google apps, providing some privacy.

PPS: I might later do a build myself with the required patches builtin, but this will take some time.

**Comment by tdm** [comment]
This is not a supported package.  Please try again with TWRP when it is available.
